"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
type Point = { x: number; y: number };
const size = 22;
const directions: Record<string, Point> = { ArrowUp: { x: 0, y: -1 }, ArrowDown: { x: 0, y: 1 }, ArrowLeft: { x: -1, y: 0 }, ArrowRight: { x: 1, y: 0 }, w: { x: 0, y: -1 }, s: { x: 0, y: 1 }, a: { x: -1, y: 0 }, d: { x: 1, y: 0 } };
export function SnakeGame() { const canvas = useRef<HTMLCanvasElement>(null); const snake = useRef<Point[]>([{ x: 11, y: 11 }, { x: 10, y: 11 }, { x: 9, y: 11 }]); const food = useRef<Point>({ x: 16, y: 11 }); const direction = useRef<Point>({ x: 1, y: 0 }); const queued = useRef<Point>({ x: 1, y: 0 }); const lastMove = useRef(0); const touch = useRef<Point | null>(null); const alive = useRef(true); const [score, setScore] = useState(0); const [best, setBest] = useState(0); const [name, setName] = useState("Player"); const [message, setMessage] = useState("PRESS AN ARROW OR SWIPE TO START");
  const reset = useCallback(() => { snake.current = [{ x: 11, y: 11 }, { x: 10, y: 11 }, { x: 9, y: 11 }]; food.current = { x: 16, y: 11 }; direction.current = { x: 1, y: 0 }; queued.current = { x: 1, y: 0 }; alive.current = true; lastMove.current = 0; setScore(0); setMessage("RUNNING"); }, []);
  const turn = useCallback((next: Point) => { if (!alive.current) reset(); if (next.x + direction.current.x || next.y + direction.current.y) queued.current = next; setMessage("RUNNING"); }, [reset]);
  useEffect(() => { setBest(Number(localStorage.getItem("snake-best") ?? 0)); const key = (event: KeyboardEvent) => { const next = directions[event.key]; if (next) { event.preventDefault(); turn(next); } }; addEventListener("keydown", key); return () => removeEventListener("keydown", key); }, [turn]);
  useEffect(() => { let frame = 0; const loop = (time: number) => { const ctx = canvas.current?.getContext("2d"); const el = canvas.current; if (!ctx || !el) return; const cell = el.width / size; if (alive.current && message === "RUNNING" && time - lastMove.current > Math.max(55, 125 - score * 2)) { lastMove.current = time; direction.current = queued.current; const head = snake.current[0]; const next = { x: head.x + direction.current.x, y: head.y + direction.current.y }; const hit = next.x < 0 || next.y < 0 || next.x >= size || next.y >= size || snake.current.some((part) => part.x === next.x && part.y === next.y); if (hit) { alive.current = false; setMessage("SIGNAL LOST — TAP TO RESTART"); const nextBest = Math.max(best, score); setBest(nextBest); localStorage.setItem("snake-best", String(nextBest)); if (score > 0) fetch("/api/scores", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, score }) }).catch(() => undefined); } else { snake.current.unshift(next); if (next.x === food.current.x && next.y === food.current.y) { setScore((value) => value + 1); let candidate: Point; do candidate = { x: Math.floor(Math.random() * size), y: Math.floor(Math.random() * size) }; while (snake.current.some((part) => part.x === candidate.x && part.y === candidate.y)); food.current = candidate; } else snake.current.pop(); } }
      ctx.fillStyle = "#090b0a"; ctx.fillRect(0, 0, el.width, el.height); ctx.strokeStyle = "rgba(216,255,62,.055)"; ctx.lineWidth = 1; for (let i = 0; i <= size; i++) { ctx.beginPath(); ctx.moveTo(i * cell, 0); ctx.lineTo(i * cell, el.height); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0, i * cell); ctx.lineTo(el.width, i * cell); ctx.stroke(); } ctx.shadowBlur = 18; ctx.shadowColor = "#d8ff3e"; snake.current.forEach((part, index) => { ctx.fillStyle = index ? `rgba(216,255,62,${Math.max(.24, 1 - index / snake.current.length)})` : "#f1efe8"; ctx.fillRect(part.x * cell + 2, part.y * cell + 2, cell - 4, cell - 4); }); ctx.fillStyle = "#ff4d75"; ctx.shadowColor = "#ff4d75"; ctx.beginPath(); ctx.arc((food.current.x + .5) * cell, (food.current.y + .5) * cell, cell * .25, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; frame = requestAnimationFrame(loop); }; frame = requestAnimationFrame(loop); return () => cancelAnimationFrame(frame); }, [best, message, name, score]);
  return <main className="game-shell"><header><Link href="/#playground">← Portfolio</Link><span>PLAYGROUND / 001</span><Link href="/playground/leaderboard">Leaderboard ↗</Link></header><section className="game-layout"><div className="game-copy"><p className="kicker">NEON SNAKE</p><h1>Eat the<br /><em>signal.</em></h1><p>Arrow keys or WASD. Swipe on mobile. Don&apos;t touch the edges—or yourself.</p><label>Leaderboard name<input value={name} maxLength={24} onChange={(e) => setName(e.target.value)} /></label><div className="scoreboard"><span>Score <b>{String(score).padStart(2, "0")}</b></span><span>Best <b>{String(best).padStart(2, "0")}</b></span></div></div><button className="canvas-button" onClick={() => !alive.current && reset()} onTouchStart={(e) => { const t = e.touches[0]; touch.current = { x: t.clientX, y: t.clientY }; }} onTouchEnd={(e) => { if (!touch.current) return; const t = e.changedTouches[0]; const dx = t.clientX - touch.current.x; const dy = t.clientY - touch.current.y; turn(Math.abs(dx) > Math.abs(dy) ? { x: Math.sign(dx), y: 0 } : { x: 0, y: Math.sign(dy) }); touch.current = null; }} aria-label="Snake game canvas"><canvas ref={canvas} width={660} height={660} /><span>{message}</span></button></section></main>; }
